postgres :
  image : postgres:9.4.5
  container_name : forest_movies
  ports :
    - "5445:5432"
  environment:
    - POSTGRES_DB=forest_movies
    - POSTGRES_USER=forest
    - POSTGRES_PASSWORD=secret
  volumes:
    - /Users/seyz/workspace/internal/forest-movies/db/csv:/tmp/foo
